### ISSUE TITLE
place of Odoo Integration documentation

### ISSUE THREAD

**Issue by legalsylvain** [vuestorefront/odoo#7]
### Provide a description of requested docs changes

hi all, 

Just took a look on this project that looks promising ! 
there is a link to the documentation https://docs.vuestorefront.io/odoo in the main readme file but it returns a 404. 

do you know where is the documentation ? 

kind regards.

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by odranoelBR** [comment]
Hi @legalsylvain !
Thanks for the report, we are publishing rc1 soon, the docs will be fixed.

**Comment by odranoelBR** [comment]
Done!
